version: 2

project_name: git-wt

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - main: ./cmd/git-wt
    binary: git-wt
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/raisedadead/git-wt/internal/commands.version={{.Version}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
      - man/*
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

brews:
  - repository:
      owner: raisedadead
      name: homebrew-tap
    homepage: https://github.com/raisedadead/git-wt
    description: Git worktree manager with bare repo support
    license: MIT
    extra_files:
      - glob: man/git-wt.1
    install: |
      bin.install "git-wt"
      man1.install "man/git-wt.1"
    test: |
      system "#{bin}/git-wt", "--version"
